learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Define URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = "learning_logs"
urlpatterns = [
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    path("new_topic/", views.new_topic, name="new_topic"),
    path("edit_topic/<int:topic_id>/", views.edit_topic, name="edit_topic"),
    path("delete_topic/<int:topic_id>/", views.delete_topic, name="delete_topic"),
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
    path("delete_entry/<int:entry_id>/", views.delete_entry, name="delete_entry"),
]

users/urls.py
"""Define URL patterns for users."""
from django.urls import include, path

from . import views

app_name = "users"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "topics"

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Information about progress in learning."""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Entry, Topic


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}  # empty label


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from .forms import EntryForm, TopicForm
from .models import Entry, Topic


def index(request):
    """The home page for Learning Log app."""
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)

    _check_topic_owner(topic.owner, request.user)

    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


def edit_topic(request, topic_id):
    """Edit an existing topic."""
    topic = get_object_or_404(Topic, id=topic_id)

    _check_topic_owner(topic.owner, request.user)

    if request.method != "POST":
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topics")

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/edit_topic.html", context)


@login_required
def delete_topic(request, topic_id):
    """Delete a topic."""
    topic = get_object_or_404(Topic, id=topic_id)
    entires = topic.entry_set.all()

    _check_topic_owner(topic.owner, request.user)

    if request.method == "POST":
        topic.delete()
        return redirect("learning_logs:topics")

    context = {"topic": topic, "entries": entires}
    return render(request, "learning_logs/delete_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = get_object_or_404(Topic, id=topic_id)

    _check_topic_owner(topic.owner, request.user)

    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic

    _check_topic_owner(topic.owner, request.user)

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)


@login_required
def delete_entry(request, entry_id):
    """Delete an existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic

    _check_topic_owner(topic.owner, request.user)

    if request.method == "POST":
        entry.delete()
        return redirect("learning_logs:topic", topic_id=topic.id)

    context = {"entry": entry, "topic": topic}
    return render(request, "learning_logs/delete_entry.html", context)


def _check_topic_owner(owner, user):
    """Check if user is the owner of the topic."""
    if owner != user:
        raise Http404

users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def register(request):
    """Register a new user."""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("learning_logs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang="pl">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
</head>

<body data-bs-theme="dark">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <nav class="navbar navbar-expand-lg bg-body-tertiary rounded">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Tematy</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item me-4">
            <span class="navbar-text d-none d-lg-block">Witaj, {{user.username}}.</span>
          </li>
          <form action="{% url 'users:logout' %}" method="post" class="my-auto">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              Wyloguj się</button>
          </form>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Rejestruj</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Zaloguj</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-4 mt-4 mb-4 border-bottom">
      {% block page_header %} {% endblock page_header%}
    </div>
    <div>{% block content %} {% endblock content%}</div>
  </main>
</body>

</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}

{% block page_header %}
<h1>Potwierdzenie usunięcia wpisu</h1>
<h4><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h4>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:delete_entry' entry.id %}" method="post">
    {% csrf_token %}
    <p><b>Data dodania:</b> {{ entry.date_added }}</p>
    <p><b>Zawartość:</b> {{ entry.text }}</p>
    <button name="submit" class="btn btn-danger">Usuń</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/delete_topic.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}

{% block page_header %}
<h1>Potwierdzenie usunięcia tematu</h1>
<h4><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h4>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:delete_topic' topic.id %}" method="post">
    {% csrf_token %}
    <p><b>Data dodania:</b> {{ topic.date_added }}</p>
    {% if entries %}
    <p>Wspisy pod tematem (zostaną również usunięte):</p>
    <ul>
        {% for entry in entries %}
        <li>{{ entry.text }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Wspisy pod tematem nie istnieją.</p>
    {% endif %}
    <button name="submit" class="btn btn-danger">Usuń</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %} 
{% load crispy_forms_tags %}

{% block page_header %}
<h1>Edycja wpisu</h1>
<h4><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h4>
{% endblock page_header %}

{% block content %}
<p>Edycja wpisu:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
  {% csrf_token %} {{ form | crispy }}
  <button name="submit" class="btn btn-primary">Zapisz zmiany</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}

{% block page_header %}
<h1>Edytuj temat</h1>
<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
  {% csrf_token %} {{ form | crispy }}
  <button type="submit" class="btn btn-primary">Edytuj</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %} {% block page_header %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded mt-3">
    <div class="col-sm-8 mx-auto">
      <h1>Monitoruj postępy w nauce</h1>
      <p class="lead">Załóż konto, aby rozpocząć korzystanie z aplikacji Learning Log oraz wyświetlić listę poznawanych
        tematów. Gdy nauczysz się czegoś nowego na dany temat, utwórz wpis podsumowujący to, czego się nauczyłeś.</p>
      {% if user.is_authenticated %}
      <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">Zobacz tematy &raquo;</a>
      {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Zarejestruj konto &raquo;</a>
      {% endif %}
    </div>
  </div>
</main>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}

{% block page_header %}
<h1>Dodaj nowy wpis</h1>
<h4><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h4>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
  {% csrf_token %} {{ form | crispy }}
  <button type="submit" class="btn btn-primary">Dodaj wpis</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}

{% block page_header %}
<h1>Dodaj nowy temat</h1>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="post">
  {% csrf_token %} {{ form | crispy }}
  <button type="submit" class="btn btn-primary">Dodaj temat</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1>{{ topic }}</h1>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Dodaj nowy wpis</a>
{% endblock page_header %}

{% block content %}
<ul>
  {% for entry in entries %}
  <div class="card mb-4">
    <h4 class="card-header">{{entry.date_added | date:"d E Y H:i"}}
      <div class="float-end">
        <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-outline-danger btn-sm">Usuń</a>
        <a href="{% url 'learning_logs:edit_entry' entry.id %}" class="btn btn-secondary btn-sm">Edytuj</a>
      </div>
      </h4>
    <div class="card-body">
      <p class="card-text">{{ entry.text | linebreaks}}</p>
    </div>
  </div>
  {% empty %}
  <h5>Nie ma jeszcze wpisów do tego tematu.</h5>
  {% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1>Tematy</h1>
<a href="{% url 'learning_logs:new_topic' %}">Dodaj nowy temat</a>
{% endblock page_header %}

{% block content %}
<ul class="list-group">
  {% for topic in topics %}
  <li class="list-group-item">
    <h4>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      <div class="float-end">
        <a href="{% url 'learning_logs:delete_topic' topic.id %}" class="btn btn-outline-danger btn-sm">Usuń</a>
        <a href="{% url 'learning_logs:edit_topic' topic.id %}" class="btn btn-outline-secondary btn-sm">Edytuj</a>
      </div>
    </h4>
  </li>
  {% empty %}
  <li><h4>Nie został dodany jeszcze żaden temat.</h4></li>
  {% endfor %}
</ul>
{% endblock content %}